# Generated by Django 4.2.1 on 2023-09-07 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='message.message', verbose_name='Сообщение'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
