# Generated by Django 4.2.1 on 2023-09-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='slug')),
                ('text', models.TextField(blank=True, null=True, verbose_name='содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_image/', verbose_name='изображение')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('view_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='публикация')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ('view_count',),
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_text', models.TextField(blank=True, null=True, verbose_name='контакты')),
            ],
        ),
    ]
